[package]
name = "tobot-discord-edge"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tobot-envelope = { path = "../../crates/tobot-envelope" }

[lints]
workspace = true
