[package]
name = "tobot-installation"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
serde.workspace = true
tobot-identity = { path = "../tobot-identity" }
url.workspace = true
uuid.workspace = true

[lints]
workspace = true
