CREATE TABLE `canvas_event_settings` (
	`guild_id` text NOT NULL,
	`event_type` text NOT NULL,
	`channel_id` text,
	`is_enabled` integer DEFAULT false NOT NULL,
	`background_url` text,
	`bg_filepath` text,
	`blur_amount` integer DEFAULT 4 NOT NULL,
	`primary_text` text DEFAULT '¡Hasta pronto!' NOT NULL,
	`secondary_text` text DEFAULT '{username}' NOT NULL,
	`message_content` text DEFAULT '{user}' NOT NULL,
	`avatar_x` integer DEFAULT 960 NOT NULL,
	`avatar_y` integer DEFAULT 380 NOT NULL,
	`avatar_size` integer DEFAULT 280 NOT NULL,
	`avatar_border_width` integer DEFAULT 8 NOT NULL,
	`avatar_border_color` text DEFAULT '#FFFFFF' NOT NULL,
	`text_x` integer DEFAULT 960 NOT NULL,
	`text_y` integer DEFAULT 560 NOT NULL,
	`font_size` integer DEFAULT 64 NOT NULL,
	`text_color` text DEFAULT '#FFFFFF' NOT NULL,
	`text_layers` text,
	`updated_at` integer NOT NULL,
	PRIMARY KEY(`guild_id`, `event_type`),
	FOREIGN KEY (`guild_id`) REFERENCES `guild_settings`(`guild_id`) ON UPDATE no action ON DELETE cascade
);
