[package]
name = "tobot-discord-adapter"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
async-trait.workspace = true
reqwest.workspace = true
serde.workspace = true
thiserror.workspace = true
twilight-http.workspace = true
twilight-model.workspace = true

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true
