CREATE TABLE "action_logs" (
	"id" text PRIMARY KEY NOT NULL,
	"guild_id" text NOT NULL,
	"category" text NOT NULL,
	"event_type" text NOT NULL,
	"executor_id" text,
	"executor_tag" text,
	"target_id" text,
	"target_tag" text,
	"channel_id" text,
	"summary" text DEFAULT '' NOT NULL,
	"details" text DEFAULT '{}' NOT NULL,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "action_logs_config" (
	"guild_id" text PRIMARY KEY NOT NULL,
	"enabled" boolean DEFAULT false NOT NULL,
	"routing_mode" text DEFAULT 'GLOBAL' NOT NULL,
	"global_channel_id" text,
	"channels_mapping" text DEFAULT '{}' NOT NULL,
	"ignored_channels" text DEFAULT '[]' NOT NULL,
	"ignored_roles" text DEFAULT '[]' NOT NULL,
	"ignore_bots" boolean DEFAULT true NOT NULL,
	"enabled_events" text DEFAULT '{}' NOT NULL,
	"data_retention_days" integer DEFAULT 14 NOT NULL,
	"webhooks_mapping" text DEFAULT '{}' NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "auto_delete_config" (
	"guild_id" text PRIMARY KEY NOT NULL,
	"enabled" boolean DEFAULT false NOT NULL,
	"rules" text DEFAULT '[]' NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "auto_mod_config" (
	"guild_id" text PRIMARY KEY NOT NULL,
	"enabled" boolean DEFAULT false NOT NULL,
	"filters" text DEFAULT '{}' NOT NULL,
	"ignored_roles" text DEFAULT '[]' NOT NULL,
	"ignored_channels" text DEFAULT '[]' NOT NULL,
	"log_channel_id" text,
	"warn_decay_days" integer DEFAULT 30 NOT NULL,
	"punishments" text DEFAULT '[]' NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "auto_roles" (
	"guild_id" text PRIMARY KEY NOT NULL,
	"human_roles" text DEFAULT '[]' NOT NULL,
	"bot_roles" text DEFAULT '[]' NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "autoroles_registry" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "autoroles_registry_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"guild_id" text NOT NULL,
	"channel_id" text NOT NULL,
	"message_id" text NOT NULL,
	"title" text DEFAULT 'Autoroles' NOT NULL,
	"type" text DEFAULT 'BUTTONS' NOT NULL,
	"roles_mapping" text DEFAULT '[]' NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "bot_presence_settings" (
	"id" text PRIMARY KEY DEFAULT 'default' NOT NULL,
	"status" text DEFAULT 'online' NOT NULL,
	"activity_type" text DEFAULT 'Playing' NOT NULL,
	"activity_name" text DEFAULT '' NOT NULL,
	"stream_url" text,
	"state" text DEFAULT '' NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "canvas_event_settings" (
	"guild_id" text NOT NULL,
	"event_type" text NOT NULL,
	"channel_id" text,
	"is_enabled" boolean DEFAULT false NOT NULL,
	"background_url" text,
	"bg_filepath" text,
	"blur_amount" integer DEFAULT 4 NOT NULL,
	"primary_text" text DEFAULT '¡Hasta pronto!' NOT NULL,
	"secondary_text" text DEFAULT '{username}' NOT NULL,
	"message_content" text DEFAULT '{user}' NOT NULL,
	"avatar_x" integer DEFAULT 960 NOT NULL,
	"avatar_y" integer DEFAULT 380 NOT NULL,
	"avatar_size" integer DEFAULT 280 NOT NULL,
	"avatar_border_width" integer DEFAULT 8 NOT NULL,
	"avatar_border_color" text DEFAULT '#FFFFFF' NOT NULL,
	"text_x" integer DEFAULT 960 NOT NULL,
	"text_y" integer DEFAULT 560 NOT NULL,
	"font_size" integer DEFAULT 64 NOT NULL,
	"text_color" text DEFAULT '#FFFFFF' NOT NULL,
	"text_layers" text,
	"updated_at" timestamp with time zone NOT NULL,
	CONSTRAINT "canvas_event_settings_guild_id_event_type_pk" PRIMARY KEY("guild_id","event_type")
);
--> statement-breakpoint
CREATE TABLE "custom_commands" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "custom_commands_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"guild_id" text NOT NULL,
	"name" text NOT NULL,
	"description" text DEFAULT 'Comando personalizado' NOT NULL,
	"response_data" text DEFAULT '{}' NOT NULL,
	"options" text DEFAULT '{}' NOT NULL,
	"permissions" text DEFAULT '{}' NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "default_command_permissions" (
	"guild_id" text NOT NULL,
	"command_name" text NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	"allowed_roles" text DEFAULT '[]' NOT NULL,
	"ignored_channels" text DEFAULT '[]' NOT NULL,
	"ephemeral" boolean DEFAULT false NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	CONSTRAINT "default_command_permissions_guild_id_command_name_pk" PRIMARY KEY("guild_id","command_name")
);
--> statement-breakpoint
CREATE TABLE "economy_casino" (
	"guild_id" text PRIMARY KEY NOT NULL,
	"is_active" boolean DEFAULT false NOT NULL,
	"min_bet" integer DEFAULT 10 NOT NULL,
	"max_bet" integer DEFAULT 10000 NOT NULL,
	"coinflip" text DEFAULT '{}' NOT NULL,
	"roulette" text DEFAULT '{}' NOT NULL,
	"blackjack" text DEFAULT '{}' NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "economy_config" (
	"guild_id" text PRIMARY KEY NOT NULL,
	"is_active" boolean DEFAULT false NOT NULL,
	"currency_name" text DEFAULT 'Adobos Coins' NOT NULL,
	"currency_symbol" text DEFAULT '🪙' NOT NULL,
	"start_balance" integer DEFAULT 0 NOT NULL,
	"transfer_tax" integer DEFAULT 0 NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "economy_cooldowns" (
	"guild_id" text NOT NULL,
	"user_id" text NOT NULL,
	"command_key" text NOT NULL,
	"available_at" timestamp with time zone NOT NULL,
	CONSTRAINT "economy_cooldowns_guild_id_user_id_command_key_pk" PRIMARY KEY("guild_id","user_id","command_key")
);
--> statement-breakpoint
CREATE TABLE "economy_income" (
	"guild_id" text PRIMARY KEY NOT NULL,
	"daily_pay" integer DEFAULT 100 NOT NULL,
	"weekly_pay" integer DEFAULT 500 NOT NULL,
	"monthly_pay" integer DEFAULT 2000 NOT NULL,
	"streak_enabled" boolean DEFAULT false NOT NULL,
	"streak_bonus_percent" integer DEFAULT 5 NOT NULL,
	"role_salaries" text DEFAULT '[]' NOT NULL,
	"jobs" text DEFAULT '[]' NOT NULL,
	"crimes" text DEFAULT '[]' NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "economy_owned_channels" (
	"id" text PRIMARY KEY NOT NULL,
	"guild_id" text NOT NULL,
	"user_id" text NOT NULL,
	"channel_id" text NOT NULL,
	"item_id" text,
	"purchase_id" text,
	"expires_at" timestamp with time zone,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "economy_owned_roles" (
	"id" text PRIMARY KEY NOT NULL,
	"guild_id" text NOT NULL,
	"user_id" text NOT NULL,
	"role_id" text NOT NULL,
	"item_id" text,
	"purchase_id" text,
	"expires_at" timestamp with time zone,
	"delete_role_on_expire" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "economy_purchases" (
	"id" text PRIMARY KEY NOT NULL,
	"guild_id" text NOT NULL,
	"user_id" text NOT NULL,
	"item_id" text NOT NULL,
	"item_name" text NOT NULL,
	"price_paid" integer NOT NULL,
	"status" text DEFAULT 'fulfilled' NOT NULL,
	"metadata" text DEFAULT '{}' NOT NULL,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "economy_shop_items" (
	"id" text PRIMARY KEY NOT NULL,
	"guild_id" text NOT NULL,
	"name" text NOT NULL,
	"description" text DEFAULT '' NOT NULL,
	"price" integer DEFAULT 0 NOT NULL,
	"icon" text DEFAULT '🛒' NOT NULL,
	"stock" integer,
	"rewards" text DEFAULT '{}' NOT NULL,
	"action_sequence" text DEFAULT '[]',
	"reward_type" text,
	"reward_config" text DEFAULT '{}',
	"enabled" boolean DEFAULT true NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "economy_user_boosts" (
	"id" text PRIMARY KEY NOT NULL,
	"guild_id" text NOT NULL,
	"user_id" text NOT NULL,
	"module" text NOT NULL,
	"multiplier" integer NOT NULL,
	"expires_at" timestamp with time zone,
	"purchase_id" text,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "embed_templates" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "embed_templates_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"guild_id" text NOT NULL,
	"name" text NOT NULL,
	"embed_data" text NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "form_responses" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "form_responses_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"form_id" integer NOT NULL,
	"guild_id" text NOT NULL,
	"user_id" text NOT NULL,
	"username" text DEFAULT '' NOT NULL,
	"display_name" text DEFAULT '' NOT NULL,
	"avatar_url" text,
	"answers" text DEFAULT '[]' NOT NULL,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "guild_forms" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "guild_forms_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"guild_id" text NOT NULL,
	"modal_title" text DEFAULT 'Formulario' NOT NULL,
	"button_label" text DEFAULT 'Abrir formulario' NOT NULL,
	"embed_title" text DEFAULT 'Formulario del servidor' NOT NULL,
	"embed_description" text DEFAULT 'Haz clic en el botón para completar el formulario.' NOT NULL,
	"embed_color" text DEFAULT '#5865F2' NOT NULL,
	"embed_image_url" text,
	"embed_thumbnail_url" text,
	"publish_channel_id" text,
	"reception_channel_id" text,
	"questions" text DEFAULT '[]' NOT NULL,
	"cooldown_minutes" integer DEFAULT 0 NOT NULL,
	"published_channel_id" text,
	"published_message_id" text,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "guild_settings" (
	"guild_id" text PRIMARY KEY NOT NULL,
	"prefix" text DEFAULT '!' NOT NULL,
	"log_channel_id" text,
	"welcome_enabled" boolean DEFAULT false NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "interactive_forms" (
	"guild_id" text PRIMARY KEY NOT NULL,
	"modal_title" text DEFAULT 'Formulario' NOT NULL,
	"button_label" text DEFAULT 'Abrir formulario' NOT NULL,
	"embed_title" text DEFAULT 'Formulario del servidor' NOT NULL,
	"embed_description" text DEFAULT 'Haz clic en el botón para completar el formulario.' NOT NULL,
	"embed_color" text DEFAULT '#5865F2' NOT NULL,
	"publish_channel_id" text,
	"reception_channel_id" text,
	"questions" text DEFAULT '[]' NOT NULL,
	"published_channel_id" text,
	"published_message_id" text,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "mod_logs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "mod_logs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"guild_id" text NOT NULL,
	"action" text NOT NULL,
	"target_user_id" text,
	"target_channel_id" text,
	"moderator_id" text NOT NULL,
	"reason" text DEFAULT '' NOT NULL,
	"meta" text,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "oauth_states" (
	"state" text PRIMARY KEY NOT NULL,
	"code_verifier" text NOT NULL,
	"expires_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "panel_sessions" (
	"id" text PRIMARY KEY NOT NULL,
	"user_id" text NOT NULL,
	"access_token_enc" text NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "panel_users" (
	"user_id" text PRIMARY KEY NOT NULL,
	"username" text NOT NULL,
	"global_name" text,
	"avatar" text,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "plugin_pokemon_config" (
	"guild_id" text PRIMARY KEY NOT NULL,
	"is_active" boolean DEFAULT false NOT NULL,
	"default_generation" integer DEFAULT 9 NOT NULL,
	"language" text DEFAULT 'es' NOT NULL,
	"embed_color" text DEFAULT '#EF4444' NOT NULL,
	"force_ephemeral" boolean DEFAULT true NOT NULL,
	"allowed_channels" text DEFAULT '[]' NOT NULL,
	"allowed_roles" text DEFAULT '[]' NOT NULL,
	"commands" text DEFAULT '{}' NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "plugins_enabled" (
	"guild_id" text NOT NULL,
	"plugin_name" text NOT NULL,
	"enabled" boolean DEFAULT false NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	CONSTRAINT "plugins_enabled_guild_id_plugin_name_pk" PRIMARY KEY("guild_id","plugin_name")
);
--> statement-breakpoint
CREATE TABLE "reaction_roles" (
	"guild_id" text NOT NULL,
	"channel_id" text NOT NULL,
	"message_id" text NOT NULL,
	"emoji_key" text NOT NULL,
	"role_id" text NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	CONSTRAINT "reaction_roles_message_id_emoji_key_pk" PRIMARY KEY("message_id","emoji_key")
);
--> statement-breakpoint
CREATE TABLE "reaction_roles_menus" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "reaction_roles_menus_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"guild_id" text NOT NULL,
	"channel_id" text NOT NULL,
	"message_id" text NOT NULL,
	"mode" text DEFAULT 'reactions' NOT NULL,
	"roles_mapping" text DEFAULT '[]' NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "scheduled_messages" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "scheduled_messages_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"guild_id" text NOT NULL,
	"channel_id" text NOT NULL,
	"timezone" text DEFAULT 'UTC' NOT NULL,
	"frequency" text DEFAULT '{}' NOT NULL,
	"embed_data" text DEFAULT '{}' NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "sent_embeds" (
	"id" text PRIMARY KEY NOT NULL,
	"guild_id" text NOT NULL,
	"channel_id" text NOT NULL,
	"message_id" text NOT NULL,
	"title" text,
	"embed_data" text NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "user_economy" (
	"guild_id" text NOT NULL,
	"user_id" text NOT NULL,
	"wallet" integer DEFAULT 0 NOT NULL,
	"bank" integer DEFAULT 0 NOT NULL,
	"daily_streak" integer DEFAULT 0 NOT NULL,
	"last_daily_at" timestamp with time zone,
	"last_weekly_at" timestamp with time zone,
	"last_monthly_at" timestamp with time zone,
	"updated_at" timestamp with time zone NOT NULL,
	CONSTRAINT "user_economy_guild_id_user_id_pk" PRIMARY KEY("guild_id","user_id")
);
--> statement-breakpoint
CREATE TABLE "user_xp" (
	"guild_id" text NOT NULL,
	"user_id" text NOT NULL,
	"xp" integer DEFAULT 0 NOT NULL,
	"level" integer DEFAULT 0 NOT NULL,
	"xp_frozen_until" timestamp with time zone,
	CONSTRAINT "user_xp_guild_id_user_id_pk" PRIMARY KEY("guild_id","user_id")
);
--> statement-breakpoint
CREATE TABLE "warnings" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "warnings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"guild_id" text NOT NULL,
	"user_id" text NOT NULL,
	"moderator_id" text NOT NULL,
	"reason" text NOT NULL,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "welcome_settings" (
	"guild_id" text PRIMARY KEY NOT NULL,
	"channel_id" text,
	"is_enabled" boolean DEFAULT false NOT NULL,
	"welcome_mode" text DEFAULT 'card' NOT NULL,
	"background_url" text,
	"bg_filepath" text,
	"blur_amount" integer DEFAULT 4 NOT NULL,
	"primary_text" text DEFAULT '¡Bienvenido!' NOT NULL,
	"secondary_text" text DEFAULT '{username}' NOT NULL,
	"message_content" text DEFAULT '{user}' NOT NULL,
	"avatar_x" integer DEFAULT 960 NOT NULL,
	"avatar_y" integer DEFAULT 380 NOT NULL,
	"avatar_size" integer DEFAULT 280 NOT NULL,
	"avatar_border_width" integer DEFAULT 8 NOT NULL,
	"avatar_border_color" text DEFAULT '#FFFFFF' NOT NULL,
	"text_x" integer DEFAULT 960 NOT NULL,
	"text_y" integer DEFAULT 560 NOT NULL,
	"font_size" integer DEFAULT 64 NOT NULL,
	"text_color" text DEFAULT '#FFFFFF' NOT NULL,
	"text_layers" text,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "xp_config" (
	"guild_id" text PRIMARY KEY NOT NULL,
	"enabled" boolean DEFAULT false NOT NULL,
	"text_xp_min" integer DEFAULT 15 NOT NULL,
	"text_xp_max" integer DEFAULT 25 NOT NULL,
	"cooldown_seconds" integer DEFAULT 60 NOT NULL,
	"voice_enabled" boolean DEFAULT false NOT NULL,
	"voice_xp_per_minute" integer DEFAULT 10 NOT NULL,
	"stream_multiplier" real DEFAULT 1 NOT NULL,
	"xp_multiplier" integer DEFAULT 1 NOT NULL,
	"ignored_roles" text DEFAULT '[]' NOT NULL,
	"ignored_channels" text DEFAULT '[]' NOT NULL,
	"level_up_channel_id" text,
	"custom_multipliers" text DEFAULT '[]' NOT NULL,
	"custom_channel_multipliers" text DEFAULT '[]' NOT NULL,
	"level_up_format" text DEFAULT 'TEXT' NOT NULL,
	"level_up_message" text DEFAULT '🎉 {user} subió al **nivel {level}**!' NOT NULL,
	"level_up_embed_title" text DEFAULT '¡Subida de Nivel!' NOT NULL,
	"level_up_embed_color" text DEFAULT '#34E21D' NOT NULL,
	"level_up_show_thumbnail" boolean DEFAULT true NOT NULL,
	"level_up_image" text,
	"live_leaderboard_channel_id" text,
	"live_leaderboard_message_id" text,
	"leaderboard_embed_title" text DEFAULT '🏆 Tabla de Clasificación' NOT NULL,
	"leaderboard_embed_description" text DEFAULT '' NOT NULL,
	"leaderboard_embed_color" text DEFAULT '#CA7AFF' NOT NULL,
	"leaderboard_show_thumbnail" boolean DEFAULT false NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "xp_rewards" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "xp_rewards_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"guild_id" text NOT NULL,
	"level" integer NOT NULL,
	"role_id" text NOT NULL
);
--> statement-breakpoint
ALTER TABLE "action_logs" ADD CONSTRAINT "action_logs_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "action_logs_config" ADD CONSTRAINT "action_logs_config_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auto_delete_config" ADD CONSTRAINT "auto_delete_config_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auto_mod_config" ADD CONSTRAINT "auto_mod_config_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auto_roles" ADD CONSTRAINT "auto_roles_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "autoroles_registry" ADD CONSTRAINT "autoroles_registry_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "canvas_event_settings" ADD CONSTRAINT "canvas_event_settings_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "custom_commands" ADD CONSTRAINT "custom_commands_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "default_command_permissions" ADD CONSTRAINT "default_command_permissions_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "economy_casino" ADD CONSTRAINT "economy_casino_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "economy_config" ADD CONSTRAINT "economy_config_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "economy_cooldowns" ADD CONSTRAINT "economy_cooldowns_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "economy_income" ADD CONSTRAINT "economy_income_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "economy_owned_channels" ADD CONSTRAINT "economy_owned_channels_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "economy_owned_roles" ADD CONSTRAINT "economy_owned_roles_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "economy_purchases" ADD CONSTRAINT "economy_purchases_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "economy_shop_items" ADD CONSTRAINT "economy_shop_items_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "economy_user_boosts" ADD CONSTRAINT "economy_user_boosts_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "embed_templates" ADD CONSTRAINT "embed_templates_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "form_responses" ADD CONSTRAINT "form_responses_form_id_guild_forms_id_fk" FOREIGN KEY ("form_id") REFERENCES "public"."guild_forms"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "form_responses" ADD CONSTRAINT "form_responses_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "guild_forms" ADD CONSTRAINT "guild_forms_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "interactive_forms" ADD CONSTRAINT "interactive_forms_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "mod_logs" ADD CONSTRAINT "mod_logs_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "panel_sessions" ADD CONSTRAINT "panel_sessions_user_id_panel_users_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."panel_users"("user_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "plugin_pokemon_config" ADD CONSTRAINT "plugin_pokemon_config_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "plugins_enabled" ADD CONSTRAINT "plugins_enabled_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "reaction_roles" ADD CONSTRAINT "reaction_roles_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "reaction_roles_menus" ADD CONSTRAINT "reaction_roles_menus_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "scheduled_messages" ADD CONSTRAINT "scheduled_messages_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sent_embeds" ADD CONSTRAINT "sent_embeds_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_economy" ADD CONSTRAINT "user_economy_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_xp" ADD CONSTRAINT "user_xp_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "warnings" ADD CONSTRAINT "warnings_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "welcome_settings" ADD CONSTRAINT "welcome_settings_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "xp_config" ADD CONSTRAINT "xp_config_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "xp_rewards" ADD CONSTRAINT "xp_rewards_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_action_logs_guild_created" ON "action_logs" USING btree ("guild_id","created_at");--> statement-breakpoint
CREATE INDEX "economy_owned_channels_user_idx" ON "economy_owned_channels" USING btree ("guild_id","user_id");--> statement-breakpoint
CREATE INDEX "economy_owned_roles_user_idx" ON "economy_owned_roles" USING btree ("guild_id","user_id");--> statement-breakpoint
CREATE INDEX "economy_purchases_guild_user_idx" ON "economy_purchases" USING btree ("guild_id","user_id");--> statement-breakpoint
CREATE INDEX "economy_shop_items_guild_idx" ON "economy_shop_items" USING btree ("guild_id");--> statement-breakpoint
CREATE INDEX "economy_user_boosts_lookup_idx" ON "economy_user_boosts" USING btree ("guild_id","user_id","module");--> statement-breakpoint
CREATE INDEX "idx_form_responses_form" ON "form_responses" USING btree ("form_id","created_at");--> statement-breakpoint
CREATE INDEX "idx_mod_logs_guild" ON "mod_logs" USING btree ("guild_id","created_at");--> statement-breakpoint
CREATE INDEX "idx_panel_sessions_user" ON "panel_sessions" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_sent_embeds_guild" ON "sent_embeds" USING btree ("guild_id","created_at");--> statement-breakpoint
CREATE INDEX "idx_warnings_guild_user" ON "warnings" USING btree ("guild_id","user_id");