CREATE TABLE "action_logs" (
	"id" text PRIMARY KEY NOT NULL,
	"guild_id" text NOT NULL,
	"category" text NOT NULL,
	"event_type" text NOT NULL,
	"executor_id" text,
	"executor_tag" text,
	"target_id" text,
	"target_tag" text,
	"channel_id" text,
	"summary" text DEFAULT '' NOT NULL,
	"details" text DEFAULT '{}' NOT NULL,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "action_logs_config" (
	"guild_id" text PRIMARY KEY NOT NULL,
	"enabled" boolean DEFAULT false NOT NULL,
	"routing_mode" text DEFAULT 'GLOBAL' NOT NULL,
	"global_channel_id" text,
	"channels_mapping" text DEFAULT '{}' NOT NULL,
	"ignored_channels" text DEFAULT '[]' NOT NULL,
	"ignored_roles" text DEFAULT '[]' NOT NULL,
	"ignore_bots" boolean DEFAULT true NOT NULL,
	"enabled_events" text DEFAULT '{}' NOT NULL,
	"data_retention_days" integer DEFAULT 14 NOT NULL,
	"webhooks_mapping" text DEFAULT '{}' NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "anti_raid_settings" (
	"guild_id" text PRIMARY KEY NOT NULL,
	"enabled" boolean DEFAULT false NOT NULL,
	"alert_channel_id" text,
	"join_flood_enabled" boolean DEFAULT true NOT NULL,
	"join_count" integer DEFAULT 10 NOT NULL,
	"join_window_seconds" integer DEFAULT 10 NOT NULL,
	"join_action" text DEFAULT 'kick' NOT NULL,
	"account_age_enabled" boolean DEFAULT false NOT NULL,
	"account_age_days" integer DEFAULT 7 NOT NULL,
	"account_age_action" text DEFAULT 'kick' NOT NULL,
	"lockdown_join_action" text DEFAULT 'timeout' NOT NULL,
	"timeout_seconds" integer DEFAULT 3600 NOT NULL,
	"whitelist_role_ids" text DEFAULT '[]' NOT NULL,
	"nuke_enabled" boolean DEFAULT false NOT NULL,
	"nuke_window_seconds" integer DEFAULT 10 NOT NULL,
	"nuke_punishment" text DEFAULT 'strip' NOT NULL,
	"nuke_thresholds" text DEFAULT '{}' NOT NULL,
	"nuke_whitelist_user_ids" text DEFAULT '[]' NOT NULL,
	"nuke_whitelist_role_ids" text DEFAULT '[]' NOT NULL,
	"lockdown_active" boolean DEFAULT false NOT NULL,
	"lockdown_started_at" timestamp with time zone,
	"lockdown_by_user_id" text,
	"lockdown_snapshot" text DEFAULT '[]' NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "auto_delete_config" (
	"guild_id" text PRIMARY KEY NOT NULL,
	"enabled" boolean DEFAULT false NOT NULL,
	"rules" text DEFAULT '[]' NOT NULL,
	"timezone" text DEFAULT 'UTC' NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "auto_delete_pending" (
	"guild_id" text NOT NULL,
	"channel_id" text NOT NULL,
	"message_id" text NOT NULL,
	"rule_channel_id" text NOT NULL,
	"delete_at" timestamp with time zone NOT NULL,
	CONSTRAINT "auto_delete_pending_guild_id_message_id_pk" PRIMARY KEY("guild_id","message_id")
);
--> statement-breakpoint
CREATE TABLE "auto_mod_config" (
	"guild_id" text PRIMARY KEY NOT NULL,
	"enabled" boolean DEFAULT false NOT NULL,
	"filters" text DEFAULT '{}' NOT NULL,
	"ignored_roles" text DEFAULT '[]' NOT NULL,
	"ignored_channels" text DEFAULT '[]' NOT NULL,
	"log_channel_id" text,
	"warn_decay_days" integer DEFAULT 30 NOT NULL,
	"warn_on_hit" boolean DEFAULT true NOT NULL,
	"dm_on_hit" boolean DEFAULT true NOT NULL,
	"skip_staff" boolean DEFAULT false NOT NULL,
	"punishments" text DEFAULT '[]' NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "auto_replies" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "auto_replies_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"guild_id" text NOT NULL,
	"trigger" text NOT NULL,
	"match_mode" text DEFAULT 'contains' NOT NULL,
	"response" text NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	"case_sensitive" boolean DEFAULT false NOT NULL,
	"whole_word" boolean DEFAULT false NOT NULL,
	"use_reply" boolean DEFAULT true NOT NULL,
	"cooldown_seconds" integer DEFAULT 0 NOT NULL,
	"allowed_channel_ids" text DEFAULT '[]' NOT NULL,
	"ignored_channel_ids" text DEFAULT '[]' NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "auto_roles" (
	"guild_id" text PRIMARY KEY NOT NULL,
	"human_roles" text DEFAULT '[]' NOT NULL,
	"bot_roles" text DEFAULT '[]' NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "autoroles_registry" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "autoroles_registry_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"guild_id" text NOT NULL,
	"channel_id" text NOT NULL,
	"message_id" text NOT NULL,
	"title" text DEFAULT 'Autoroles' NOT NULL,
	"type" text DEFAULT 'BUTTONS' NOT NULL,
	"roles_mapping" text DEFAULT '[]' NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "billing_customers" (
	"user_id" text PRIMARY KEY NOT NULL,
	"stripe_customer_id" text NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	CONSTRAINT "billing_customers_stripe_customer_id_unique" UNIQUE("stripe_customer_id")
);
--> statement-breakpoint
CREATE TABLE "bot_presence_settings" (
	"id" text PRIMARY KEY DEFAULT 'default' NOT NULL,
	"status" text DEFAULT 'online' NOT NULL,
	"activity_type" text DEFAULT 'Playing' NOT NULL,
	"activity_name" text DEFAULT '' NOT NULL,
	"stream_url" text,
	"state" text DEFAULT '' NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "canvas_event_settings" (
	"guild_id" text NOT NULL,
	"event_type" text NOT NULL,
	"channel_id" text,
	"is_enabled" boolean DEFAULT false NOT NULL,
	"background_url" text,
	"bg_filepath" text,
	"blur_amount" integer DEFAULT 4 NOT NULL,
	"primary_text" text DEFAULT 'See you soon!' NOT NULL,
	"secondary_text" text DEFAULT '{username}' NOT NULL,
	"message_content" text DEFAULT '{user}' NOT NULL,
	"avatar_x" integer DEFAULT 960 NOT NULL,
	"avatar_y" integer DEFAULT 380 NOT NULL,
	"avatar_size" integer DEFAULT 280 NOT NULL,
	"avatar_border_width" integer DEFAULT 8 NOT NULL,
	"avatar_border_color" text DEFAULT '#FFFFFF' NOT NULL,
	"text_x" integer DEFAULT 960 NOT NULL,
	"text_y" integer DEFAULT 560 NOT NULL,
	"font_size" integer DEFAULT 64 NOT NULL,
	"text_color" text DEFAULT '#FFFFFF' NOT NULL,
	"text_layers" text,
	"updated_at" timestamp with time zone NOT NULL,
	CONSTRAINT "canvas_event_settings_guild_id_event_type_pk" PRIMARY KEY("guild_id","event_type")
);
--> statement-breakpoint
CREATE TABLE "custom_commands" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "custom_commands_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"guild_id" text NOT NULL,
	"name" text NOT NULL,
	"description" text DEFAULT 'Custom command' NOT NULL,
	"response_data" text DEFAULT '{}' NOT NULL,
	"options" text DEFAULT '{}' NOT NULL,
	"permissions" text DEFAULT '{}' NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "default_command_permissions" (
	"guild_id" text NOT NULL,
	"command_name" text NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	"allowed_roles" text DEFAULT '[]' NOT NULL,
	"ignored_channels" text DEFAULT '[]' NOT NULL,
	"ephemeral" boolean DEFAULT false NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	CONSTRAINT "default_command_permissions_guild_id_command_name_pk" PRIMARY KEY("guild_id","command_name")
);
--> statement-breakpoint
CREATE TABLE "economy_blackjack_open" (
	"guild_id" text NOT NULL,
	"user_id" text NOT NULL,
	"bet" integer NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	CONSTRAINT "economy_blackjack_open_guild_id_user_id_pk" PRIMARY KEY("guild_id","user_id")
);
--> statement-breakpoint
CREATE TABLE "economy_casino" (
	"guild_id" text PRIMARY KEY NOT NULL,
	"is_active" boolean DEFAULT false NOT NULL,
	"min_bet" integer DEFAULT 10 NOT NULL,
	"max_bet" integer DEFAULT 10000 NOT NULL,
	"coinflip" text DEFAULT '{}' NOT NULL,
	"roulette" text DEFAULT '{}' NOT NULL,
	"blackjack" text DEFAULT '{}' NOT NULL,
	"slots" text DEFAULT '{}' NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "economy_config" (
	"guild_id" text PRIMARY KEY NOT NULL,
	"is_active" boolean DEFAULT false NOT NULL,
	"currency_name" text DEFAULT 'Adobos Coins' NOT NULL,
	"currency_symbol" text DEFAULT '🪙' NOT NULL,
	"start_balance" integer DEFAULT 0 NOT NULL,
	"transfer_tax" integer DEFAULT 0 NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "economy_cooldowns" (
	"guild_id" text NOT NULL,
	"user_id" text NOT NULL,
	"command_key" text NOT NULL,
	"available_at" timestamp with time zone NOT NULL,
	CONSTRAINT "economy_cooldowns_guild_id_user_id_command_key_pk" PRIMARY KEY("guild_id","user_id","command_key")
);
--> statement-breakpoint
CREATE TABLE "economy_income" (
	"guild_id" text PRIMARY KEY NOT NULL,
	"daily_pay" integer DEFAULT 100 NOT NULL,
	"weekly_pay" integer DEFAULT 500 NOT NULL,
	"monthly_pay" integer DEFAULT 2000 NOT NULL,
	"streak_enabled" boolean DEFAULT false NOT NULL,
	"streak_bonus_percent" integer DEFAULT 5 NOT NULL,
	"role_salaries" text DEFAULT '[]' NOT NULL,
	"jobs" text DEFAULT '[]' NOT NULL,
	"crimes" text DEFAULT '[]' NOT NULL,
	"rob" text DEFAULT '{}' NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "economy_owned_channels" (
	"id" text PRIMARY KEY NOT NULL,
	"guild_id" text NOT NULL,
	"user_id" text NOT NULL,
	"channel_id" text NOT NULL,
	"item_id" text,
	"purchase_id" text,
	"expires_at" timestamp with time zone,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "economy_owned_roles" (
	"id" text PRIMARY KEY NOT NULL,
	"guild_id" text NOT NULL,
	"user_id" text NOT NULL,
	"role_id" text NOT NULL,
	"item_id" text,
	"purchase_id" text,
	"expires_at" timestamp with time zone,
	"delete_role_on_expire" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "economy_purchases" (
	"id" text PRIMARY KEY NOT NULL,
	"guild_id" text NOT NULL,
	"user_id" text NOT NULL,
	"item_id" text NOT NULL,
	"item_name" text NOT NULL,
	"price_paid" integer NOT NULL,
	"status" text DEFAULT 'fulfilled' NOT NULL,
	"metadata" text DEFAULT '{}' NOT NULL,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "economy_shop_items" (
	"id" text PRIMARY KEY NOT NULL,
	"guild_id" text NOT NULL,
	"name" text NOT NULL,
	"description" text DEFAULT '' NOT NULL,
	"price" integer DEFAULT 0 NOT NULL,
	"icon" text DEFAULT '🛒' NOT NULL,
	"stock" integer,
	"rewards" text DEFAULT '{}' NOT NULL,
	"action_sequence" text DEFAULT '[]',
	"reward_type" text,
	"reward_config" text DEFAULT '{}',
	"enabled" boolean DEFAULT true NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "economy_user_boosts" (
	"id" text PRIMARY KEY NOT NULL,
	"guild_id" text NOT NULL,
	"user_id" text NOT NULL,
	"module" text NOT NULL,
	"multiplier" integer NOT NULL,
	"expires_at" timestamp with time zone,
	"purchase_id" text,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "embed_templates" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "embed_templates_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"guild_id" text NOT NULL,
	"name" text NOT NULL,
	"embed_data" text NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "form_responses" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "form_responses_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"form_id" integer NOT NULL,
	"guild_id" text NOT NULL,
	"user_id" text NOT NULL,
	"username" text DEFAULT '' NOT NULL,
	"display_name" text DEFAULT '' NOT NULL,
	"avatar_url" text,
	"answers" text DEFAULT '[]' NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"reviewed_by" text,
	"reviewed_at" timestamp with time zone,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "giveaway_entries" (
	"giveaway_id" integer NOT NULL,
	"user_id" text NOT NULL,
	"entered_at" timestamp with time zone NOT NULL,
	CONSTRAINT "giveaway_entries_giveaway_id_user_id_pk" PRIMARY KEY("giveaway_id","user_id")
);
--> statement-breakpoint
CREATE TABLE "giveaway_settings" (
	"guild_id" text PRIMARY KEY NOT NULL,
	"manager_role_ids" text DEFAULT '[]' NOT NULL,
	"dm_winners" boolean DEFAULT true NOT NULL,
	"ping_role_id" text,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "giveaways" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "giveaways_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"guild_id" text NOT NULL,
	"channel_id" text NOT NULL,
	"message_id" text,
	"prize" text NOT NULL,
	"description" text DEFAULT '' NOT NULL,
	"winner_count" integer DEFAULT 1 NOT NULL,
	"status" text DEFAULT 'scheduled' NOT NULL,
	"starts_at" timestamp with time zone NOT NULL,
	"ends_at" timestamp with time zone NOT NULL,
	"ended_at" timestamp with time zone,
	"created_by" text NOT NULL,
	"required_role_ids" text DEFAULT '[]' NOT NULL,
	"blocked_role_ids" text DEFAULT '[]' NOT NULL,
	"min_guild_age_days" integer DEFAULT 0 NOT NULL,
	"min_account_age_days" integer DEFAULT 0 NOT NULL,
	"winner_ids" text DEFAULT '[]' NOT NULL,
	"past_winner_ids" text DEFAULT '[]' NOT NULL,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "guild_entitlements" (
	"guild_id" text PRIMARY KEY NOT NULL,
	"subscription_id" integer,
	"tier" text DEFAULT 'free' NOT NULL,
	"assigned_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "guild_forms" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "guild_forms_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"guild_id" text NOT NULL,
	"modal_title" text DEFAULT 'Form' NOT NULL,
	"button_label" text DEFAULT 'Open form' NOT NULL,
	"embed_title" text DEFAULT 'Server form' NOT NULL,
	"embed_description" text DEFAULT 'Click the button to fill out the form.' NOT NULL,
	"embed_color" text DEFAULT '#5865F2' NOT NULL,
	"embed_image_url" text,
	"embed_thumbnail_url" text,
	"publish_channel_id" text,
	"reception_channel_id" text,
	"questions" text DEFAULT '[]' NOT NULL,
	"cooldown_minutes" integer DEFAULT 0 NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	"submit_mode" text DEFAULT 'cooldown' NOT NULL,
	"required_role_ids" text DEFAULT '[]' NOT NULL,
	"blocked_role_ids" text DEFAULT '[]' NOT NULL,
	"ping_role_id" text,
	"thank_you_message" text DEFAULT '' NOT NULL,
	"accept_role_id" text,
	"published_channel_id" text,
	"published_message_id" text,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "guild_settings" (
	"guild_id" text PRIMARY KEY NOT NULL,
	"prefix" text DEFAULT '!' NOT NULL,
	"log_channel_id" text,
	"welcome_enabled" boolean DEFAULT false NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "interactive_forms" (
	"guild_id" text PRIMARY KEY NOT NULL,
	"modal_title" text DEFAULT 'Form' NOT NULL,
	"button_label" text DEFAULT 'Open form' NOT NULL,
	"embed_title" text DEFAULT 'Server form' NOT NULL,
	"embed_description" text DEFAULT 'Click the button to fill out the form.' NOT NULL,
	"embed_color" text DEFAULT '#5865F2' NOT NULL,
	"publish_channel_id" text,
	"reception_channel_id" text,
	"questions" text DEFAULT '[]' NOT NULL,
	"published_channel_id" text,
	"published_message_id" text,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "mod_logs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "mod_logs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"guild_id" text NOT NULL,
	"action" text NOT NULL,
	"target_user_id" text,
	"target_channel_id" text,
	"moderator_id" text NOT NULL,
	"reason" text DEFAULT '' NOT NULL,
	"meta" text,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "oauth_states" (
	"state" text PRIMARY KEY NOT NULL,
	"code_verifier" text NOT NULL,
	"expires_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "panel_sessions" (
	"id" text PRIMARY KEY NOT NULL,
	"user_id" text NOT NULL,
	"access_token_enc" text NOT NULL,
	"refresh_token_enc" text,
	"access_expires_at" timestamp with time zone,
	"expires_at" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "panel_users" (
	"user_id" text PRIMARY KEY NOT NULL,
	"username" text NOT NULL,
	"global_name" text,
	"avatar" text,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "plugins_enabled" (
	"guild_id" text NOT NULL,
	"plugin_name" text NOT NULL,
	"enabled" boolean DEFAULT false NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	CONSTRAINT "plugins_enabled_guild_id_plugin_name_pk" PRIMARY KEY("guild_id","plugin_name")
);
--> statement-breakpoint
CREATE TABLE "reaction_roles" (
	"guild_id" text NOT NULL,
	"channel_id" text NOT NULL,
	"message_id" text NOT NULL,
	"emoji_key" text NOT NULL,
	"role_id" text NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	CONSTRAINT "reaction_roles_message_id_emoji_key_pk" PRIMARY KEY("message_id","emoji_key")
);
--> statement-breakpoint
CREATE TABLE "reaction_roles_menus" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "reaction_roles_menus_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"guild_id" text NOT NULL,
	"channel_id" text NOT NULL,
	"message_id" text NOT NULL,
	"mode" text DEFAULT 'reactions' NOT NULL,
	"roles_mapping" text DEFAULT '[]' NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "reminder_settings" (
	"guild_id" text PRIMARY KEY NOT NULL,
	"timezone" text DEFAULT 'UTC' NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "reminders" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "reminders_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"guild_id" text NOT NULL,
	"user_id" text NOT NULL,
	"channel_id" text NOT NULL,
	"message" text NOT NULL,
	"due_at" timestamp with time zone NOT NULL,
	"attempts" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "scheduled_messages" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "scheduled_messages_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"guild_id" text NOT NULL,
	"channel_id" text NOT NULL,
	"timezone" text DEFAULT 'UTC' NOT NULL,
	"frequency" text DEFAULT '{}' NOT NULL,
	"embed_data" text DEFAULT '{}' NOT NULL,
	"content" text DEFAULT '' NOT NULL,
	"ping_role_id" text,
	"is_active" boolean DEFAULT true NOT NULL,
	"next_run_at" timestamp with time zone,
	"last_sent_at" timestamp with time zone,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "sent_embeds" (
	"id" text PRIMARY KEY NOT NULL,
	"guild_id" text NOT NULL,
	"channel_id" text NOT NULL,
	"message_id" text NOT NULL,
	"title" text,
	"embed_data" text NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "starboard_posts" (
	"original_message_id" text PRIMARY KEY NOT NULL,
	"guild_id" text NOT NULL,
	"channel_id" text NOT NULL,
	"starboard_message_id" text NOT NULL,
	"star_count" integer DEFAULT 0 NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "starboard_settings" (
	"guild_id" text PRIMARY KEY NOT NULL,
	"channel_id" text,
	"emojis" text DEFAULT '["unicode:⭐"]' NOT NULL,
	"threshold" integer DEFAULT 3 NOT NULL,
	"enabled" boolean DEFAULT false NOT NULL,
	"allow_self_star" boolean DEFAULT false NOT NULL,
	"allow_bots" boolean DEFAULT false NOT NULL,
	"ignore_channel_ids" text DEFAULT '[]' NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "stream_alerts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "stream_alerts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"guild_id" text NOT NULL,
	"platform" text NOT NULL,
	"handle" text NOT NULL,
	"display_name" text NOT NULL,
	"discord_channel_id" text NOT NULL,
	"mention_role_id" text,
	"template" text DEFAULT '{name} is live: {title}
{url}' NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	"is_live" boolean DEFAULT false NOT NULL,
	"live_id" text,
	"last_title" text,
	"last_checked_at" timestamp with time zone,
	"last_live_at" timestamp with time zone,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "subscriptions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "subscriptions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" text NOT NULL,
	"stripe_customer_id" text,
	"stripe_subscription_id" text,
	"stripe_price_id" text,
	"tier" text DEFAULT 'pro' NOT NULL,
	"status" text DEFAULT 'active' NOT NULL,
	"current_period_end" timestamp with time zone,
	"cancel_at" timestamp with time zone,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	CONSTRAINT "subscriptions_stripe_subscription_id_unique" UNIQUE("stripe_subscription_id")
);
--> statement-breakpoint
CREATE TABLE "ticket_events" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ticket_events_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"ticket_id" integer NOT NULL,
	"guild_id" text NOT NULL,
	"type" text NOT NULL,
	"actor_id" text,
	"payload" text DEFAULT '{}' NOT NULL,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ticket_panels" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ticket_panels_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"guild_id" text NOT NULL,
	"channel_id" text,
	"message_id" text,
	"embed_title" text DEFAULT 'Tickets' NOT NULL,
	"embed_description" text DEFAULT 'Press a button to open a ticket.' NOT NULL,
	"embed_color" text DEFAULT '#5865F2' NOT NULL,
	"buttons" text DEFAULT '[]' NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ticket_participants" (
	"ticket_id" integer NOT NULL,
	"user_id" text NOT NULL,
	"kind" text DEFAULT 'added' NOT NULL,
	CONSTRAINT "ticket_participants_ticket_id_user_id_pk" PRIMARY KEY("ticket_id","user_id")
);
--> statement-breakpoint
CREATE TABLE "ticket_settings" (
	"guild_id" text PRIMARY KEY NOT NULL,
	"category_id" text,
	"staff_role_ids" text DEFAULT '[]' NOT NULL,
	"name_template" text DEFAULT 'ticket-{n}-{user}' NOT NULL,
	"max_open_per_user" integer DEFAULT 1 NOT NULL,
	"log_channel_id" text,
	"next_number" integer DEFAULT 1 NOT NULL,
	"opener_can_close" boolean DEFAULT true NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "tickets" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tickets_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"guild_id" text NOT NULL,
	"number" integer NOT NULL,
	"opener_id" text NOT NULL,
	"channel_id" text,
	"type_key" text NOT NULL,
	"status" text DEFAULT 'open' NOT NULL,
	"claimed_by" text,
	"reason" text,
	"close_reason" text,
	"transcript_text" text,
	"opened_at" timestamp with time zone NOT NULL,
	"closed_at" timestamp with time zone,
	"claimed_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "user_economy" (
	"guild_id" text NOT NULL,
	"user_id" text NOT NULL,
	"wallet" integer DEFAULT 0 NOT NULL,
	"bank" integer DEFAULT 0 NOT NULL,
	"daily_streak" integer DEFAULT 0 NOT NULL,
	"last_daily_at" timestamp with time zone,
	"last_weekly_at" timestamp with time zone,
	"last_monthly_at" timestamp with time zone,
	"updated_at" timestamp with time zone NOT NULL,
	CONSTRAINT "user_economy_guild_id_user_id_pk" PRIMARY KEY("guild_id","user_id")
);
--> statement-breakpoint
CREATE TABLE "user_xp" (
	"guild_id" text NOT NULL,
	"user_id" text NOT NULL,
	"xp" integer DEFAULT 0 NOT NULL,
	"level" integer DEFAULT 0 NOT NULL,
	"xp_frozen_until" timestamp with time zone,
	CONSTRAINT "user_xp_guild_id_user_id_pk" PRIMARY KEY("guild_id","user_id")
);
--> statement-breakpoint
CREATE TABLE "voice_room_generators" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "voice_room_generators_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"guild_id" text NOT NULL,
	"hub_channel_id" text NOT NULL,
	"category_id" text,
	"name_template" text DEFAULT '{user}''s room' NOT NULL,
	"default_user_limit" integer DEFAULT 0 NOT NULL,
	"default_bitrate" integer DEFAULT 0 NOT NULL,
	"auto_text" boolean DEFAULT false NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	"allowed_actions" text DEFAULT '{}' NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "voice_rooms" (
	"channel_id" text PRIMARY KEY NOT NULL,
	"guild_id" text NOT NULL,
	"generator_id" integer NOT NULL,
	"owner_id" text NOT NULL,
	"text_channel_id" text,
	"locked" boolean DEFAULT false NOT NULL,
	"ghosted" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "warnings" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "warnings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"guild_id" text NOT NULL,
	"user_id" text NOT NULL,
	"moderator_id" text NOT NULL,
	"reason" text NOT NULL,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "webhook_events" (
	"event_id" text PRIMARY KEY NOT NULL,
	"event_type" text NOT NULL,
	"processed_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "welcome_settings" (
	"guild_id" text PRIMARY KEY NOT NULL,
	"channel_id" text,
	"is_enabled" boolean DEFAULT false NOT NULL,
	"welcome_mode" text DEFAULT 'card' NOT NULL,
	"background_url" text,
	"bg_filepath" text,
	"blur_amount" integer DEFAULT 4 NOT NULL,
	"primary_text" text DEFAULT 'Welcome!' NOT NULL,
	"secondary_text" text DEFAULT '{username}' NOT NULL,
	"message_content" text DEFAULT '{user}' NOT NULL,
	"avatar_x" integer DEFAULT 960 NOT NULL,
	"avatar_y" integer DEFAULT 380 NOT NULL,
	"avatar_size" integer DEFAULT 280 NOT NULL,
	"avatar_border_width" integer DEFAULT 8 NOT NULL,
	"avatar_border_color" text DEFAULT '#FFFFFF' NOT NULL,
	"text_x" integer DEFAULT 960 NOT NULL,
	"text_y" integer DEFAULT 560 NOT NULL,
	"font_size" integer DEFAULT 64 NOT NULL,
	"text_color" text DEFAULT '#FFFFFF' NOT NULL,
	"text_layers" text,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "xp_config" (
	"guild_id" text PRIMARY KEY NOT NULL,
	"enabled" boolean DEFAULT false NOT NULL,
	"text_xp_min" integer DEFAULT 15 NOT NULL,
	"text_xp_max" integer DEFAULT 25 NOT NULL,
	"cooldown_seconds" integer DEFAULT 60 NOT NULL,
	"voice_enabled" boolean DEFAULT false NOT NULL,
	"voice_xp_per_minute" integer DEFAULT 10 NOT NULL,
	"stream_multiplier" real DEFAULT 1 NOT NULL,
	"xp_multiplier" integer DEFAULT 1 NOT NULL,
	"ignored_roles" text DEFAULT '[]' NOT NULL,
	"ignored_channels" text DEFAULT '[]' NOT NULL,
	"level_up_channel_id" text,
	"custom_multipliers" text DEFAULT '[]' NOT NULL,
	"custom_channel_multipliers" text DEFAULT '[]' NOT NULL,
	"level_up_format" text DEFAULT 'TEXT' NOT NULL,
	"level_up_message" text DEFAULT '🎉 {user} reached **level {level}**!' NOT NULL,
	"level_up_embed_title" text DEFAULT 'Level Up!' NOT NULL,
	"level_up_embed_color" text DEFAULT '#34E21D' NOT NULL,
	"level_up_show_thumbnail" boolean DEFAULT true NOT NULL,
	"level_up_image" text,
	"live_leaderboard_channel_id" text,
	"live_leaderboard_message_id" text,
	"leaderboard_embed_title" text DEFAULT '🏆 Leaderboard' NOT NULL,
	"leaderboard_embed_description" text DEFAULT '' NOT NULL,
	"leaderboard_embed_color" text DEFAULT '#CA7AFF' NOT NULL,
	"leaderboard_show_thumbnail" boolean DEFAULT false NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "xp_rewards" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "xp_rewards_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"guild_id" text NOT NULL,
	"level" integer NOT NULL,
	"role_id" text NOT NULL
);
--> statement-breakpoint
ALTER TABLE "action_logs" ADD CONSTRAINT "action_logs_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "action_logs_config" ADD CONSTRAINT "action_logs_config_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "anti_raid_settings" ADD CONSTRAINT "anti_raid_settings_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auto_delete_config" ADD CONSTRAINT "auto_delete_config_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auto_delete_pending" ADD CONSTRAINT "auto_delete_pending_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auto_mod_config" ADD CONSTRAINT "auto_mod_config_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auto_replies" ADD CONSTRAINT "auto_replies_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auto_roles" ADD CONSTRAINT "auto_roles_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "autoroles_registry" ADD CONSTRAINT "autoroles_registry_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "canvas_event_settings" ADD CONSTRAINT "canvas_event_settings_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "custom_commands" ADD CONSTRAINT "custom_commands_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "default_command_permissions" ADD CONSTRAINT "default_command_permissions_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "economy_blackjack_open" ADD CONSTRAINT "economy_blackjack_open_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "economy_casino" ADD CONSTRAINT "economy_casino_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "economy_config" ADD CONSTRAINT "economy_config_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "economy_cooldowns" ADD CONSTRAINT "economy_cooldowns_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "economy_income" ADD CONSTRAINT "economy_income_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "economy_owned_channels" ADD CONSTRAINT "economy_owned_channels_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "economy_owned_roles" ADD CONSTRAINT "economy_owned_roles_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "economy_purchases" ADD CONSTRAINT "economy_purchases_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "economy_shop_items" ADD CONSTRAINT "economy_shop_items_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "economy_user_boosts" ADD CONSTRAINT "economy_user_boosts_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "embed_templates" ADD CONSTRAINT "embed_templates_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "form_responses" ADD CONSTRAINT "form_responses_form_id_guild_forms_id_fk" FOREIGN KEY ("form_id") REFERENCES "public"."guild_forms"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "form_responses" ADD CONSTRAINT "form_responses_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "giveaway_entries" ADD CONSTRAINT "giveaway_entries_giveaway_id_giveaways_id_fk" FOREIGN KEY ("giveaway_id") REFERENCES "public"."giveaways"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "giveaway_settings" ADD CONSTRAINT "giveaway_settings_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "giveaways" ADD CONSTRAINT "giveaways_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "guild_entitlements" ADD CONSTRAINT "guild_entitlements_subscription_id_subscriptions_id_fk" FOREIGN KEY ("subscription_id") REFERENCES "public"."subscriptions"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "guild_forms" ADD CONSTRAINT "guild_forms_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "interactive_forms" ADD CONSTRAINT "interactive_forms_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "mod_logs" ADD CONSTRAINT "mod_logs_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "panel_sessions" ADD CONSTRAINT "panel_sessions_user_id_panel_users_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."panel_users"("user_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "plugins_enabled" ADD CONSTRAINT "plugins_enabled_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "reaction_roles" ADD CONSTRAINT "reaction_roles_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "reaction_roles_menus" ADD CONSTRAINT "reaction_roles_menus_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "reminder_settings" ADD CONSTRAINT "reminder_settings_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "reminders" ADD CONSTRAINT "reminders_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "scheduled_messages" ADD CONSTRAINT "scheduled_messages_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sent_embeds" ADD CONSTRAINT "sent_embeds_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "starboard_posts" ADD CONSTRAINT "starboard_posts_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "starboard_settings" ADD CONSTRAINT "starboard_settings_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stream_alerts" ADD CONSTRAINT "stream_alerts_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ticket_events" ADD CONSTRAINT "ticket_events_ticket_id_tickets_id_fk" FOREIGN KEY ("ticket_id") REFERENCES "public"."tickets"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ticket_events" ADD CONSTRAINT "ticket_events_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ticket_panels" ADD CONSTRAINT "ticket_panels_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ticket_participants" ADD CONSTRAINT "ticket_participants_ticket_id_tickets_id_fk" FOREIGN KEY ("ticket_id") REFERENCES "public"."tickets"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ticket_settings" ADD CONSTRAINT "ticket_settings_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tickets" ADD CONSTRAINT "tickets_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_economy" ADD CONSTRAINT "user_economy_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_xp" ADD CONSTRAINT "user_xp_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "voice_room_generators" ADD CONSTRAINT "voice_room_generators_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "voice_rooms" ADD CONSTRAINT "voice_rooms_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "voice_rooms" ADD CONSTRAINT "voice_rooms_generator_id_voice_room_generators_id_fk" FOREIGN KEY ("generator_id") REFERENCES "public"."voice_room_generators"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "warnings" ADD CONSTRAINT "warnings_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "welcome_settings" ADD CONSTRAINT "welcome_settings_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "xp_config" ADD CONSTRAINT "xp_config_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "xp_rewards" ADD CONSTRAINT "xp_rewards_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_action_logs_guild_created" ON "action_logs" USING btree ("guild_id","created_at");--> statement-breakpoint
CREATE INDEX "idx_auto_delete_pending_due" ON "auto_delete_pending" USING btree ("delete_at");--> statement-breakpoint
CREATE INDEX "idx_auto_delete_pending_rule" ON "auto_delete_pending" USING btree ("guild_id","rule_channel_id");--> statement-breakpoint
CREATE INDEX "idx_auto_replies_guild" ON "auto_replies" USING btree ("guild_id");--> statement-breakpoint
CREATE UNIQUE INDEX "idx_custom_commands_guild_name" ON "custom_commands" USING btree ("guild_id","name");--> statement-breakpoint
CREATE INDEX "economy_owned_channels_user_idx" ON "economy_owned_channels" USING btree ("guild_id","user_id");--> statement-breakpoint
CREATE INDEX "economy_owned_roles_user_idx" ON "economy_owned_roles" USING btree ("guild_id","user_id");--> statement-breakpoint
CREATE INDEX "economy_purchases_guild_user_idx" ON "economy_purchases" USING btree ("guild_id","user_id");--> statement-breakpoint
CREATE INDEX "economy_shop_items_guild_idx" ON "economy_shop_items" USING btree ("guild_id");--> statement-breakpoint
CREATE INDEX "economy_user_boosts_lookup_idx" ON "economy_user_boosts" USING btree ("guild_id","user_id","module");--> statement-breakpoint
CREATE INDEX "idx_form_responses_form" ON "form_responses" USING btree ("form_id","created_at");--> statement-breakpoint
CREATE INDEX "idx_form_responses_user" ON "form_responses" USING btree ("form_id","user_id","created_at");--> statement-breakpoint
CREATE INDEX "idx_giveaway_entries_giveaway" ON "giveaway_entries" USING btree ("giveaway_id");--> statement-breakpoint
CREATE INDEX "idx_giveaways_guild_status" ON "giveaways" USING btree ("guild_id","status");--> statement-breakpoint
CREATE INDEX "idx_giveaways_ends_at" ON "giveaways" USING btree ("ends_at");--> statement-breakpoint
CREATE INDEX "idx_giveaways_starts_at" ON "giveaways" USING btree ("starts_at");--> statement-breakpoint
CREATE INDEX "idx_guild_entitlements_subscription" ON "guild_entitlements" USING btree ("subscription_id");--> statement-breakpoint
CREATE INDEX "idx_mod_logs_guild" ON "mod_logs" USING btree ("guild_id","created_at");--> statement-breakpoint
CREATE INDEX "idx_panel_sessions_user" ON "panel_sessions" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_reminders_due" ON "reminders" USING btree ("due_at");--> statement-breakpoint
CREATE INDEX "idx_reminders_guild_user" ON "reminders" USING btree ("guild_id","user_id");--> statement-breakpoint
CREATE INDEX "idx_scheduled_messages_due" ON "scheduled_messages" USING btree ("is_active","next_run_at");--> statement-breakpoint
CREATE INDEX "idx_sent_embeds_guild" ON "sent_embeds" USING btree ("guild_id","created_at");--> statement-breakpoint
CREATE UNIQUE INDEX "starboard_posts_starboard_message" ON "starboard_posts" USING btree ("starboard_message_id");--> statement-breakpoint
CREATE INDEX "idx_starboard_posts_guild" ON "starboard_posts" USING btree ("guild_id");--> statement-breakpoint
CREATE UNIQUE INDEX "stream_alerts_guild_platform_handle" ON "stream_alerts" USING btree ("guild_id","platform","handle");--> statement-breakpoint
CREATE INDEX "idx_stream_alerts_guild" ON "stream_alerts" USING btree ("guild_id");--> statement-breakpoint
CREATE INDEX "idx_stream_alerts_enabled" ON "stream_alerts" USING btree ("enabled");--> statement-breakpoint
CREATE INDEX "idx_subscriptions_user" ON "subscriptions" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_ticket_events_ticket" ON "ticket_events" USING btree ("ticket_id");--> statement-breakpoint
CREATE INDEX "idx_ticket_events_guild_created" ON "ticket_events" USING btree ("guild_id","created_at");--> statement-breakpoint
CREATE INDEX "idx_ticket_panels_guild" ON "ticket_panels" USING btree ("guild_id");--> statement-breakpoint
CREATE INDEX "idx_ticket_participants_ticket" ON "ticket_participants" USING btree ("ticket_id");--> statement-breakpoint
CREATE UNIQUE INDEX "tickets_guild_number" ON "tickets" USING btree ("guild_id","number");--> statement-breakpoint
CREATE UNIQUE INDEX "tickets_channel_id_unique" ON "tickets" USING btree ("channel_id");--> statement-breakpoint
CREATE INDEX "idx_tickets_guild_status" ON "tickets" USING btree ("guild_id","status");--> statement-breakpoint
CREATE INDEX "idx_tickets_guild_opener" ON "tickets" USING btree ("guild_id","opener_id");--> statement-breakpoint
CREATE UNIQUE INDEX "voice_room_generators_guild_hub" ON "voice_room_generators" USING btree ("guild_id","hub_channel_id");--> statement-breakpoint
CREATE UNIQUE INDEX "voice_rooms_guild_owner" ON "voice_rooms" USING btree ("guild_id","owner_id");--> statement-breakpoint
CREATE INDEX "idx_voice_rooms_guild" ON "voice_rooms" USING btree ("guild_id");--> statement-breakpoint
CREATE INDEX "idx_warnings_guild_user" ON "warnings" USING btree ("guild_id","user_id");--> statement-breakpoint
CREATE UNIQUE INDEX "idx_xp_rewards_guild_level" ON "xp_rewards" USING btree ("guild_id","level");