CREATE TABLE "subscriptions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "subscriptions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" text NOT NULL,
	"tier" text DEFAULT 'pro' NOT NULL,
	"status" text DEFAULT 'active' NOT NULL,
	"current_period_end" timestamp with time zone,
	"cancel_at" timestamp with time zone,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "guild_entitlements" (
	"guild_id" text PRIMARY KEY NOT NULL,
	"subscription_id" integer,
	"tier" text DEFAULT 'free' NOT NULL,
	"assigned_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
ALTER TABLE "guild_entitlements" ADD CONSTRAINT "guild_entitlements_subscription_id_subscriptions_id_fk" FOREIGN KEY ("subscription_id") REFERENCES "public"."subscriptions"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_subscriptions_user" ON "subscriptions" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_guild_entitlements_subscription" ON "guild_entitlements" USING btree ("subscription_id");
