CREATE TABLE "voice_room_generators" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "voice_room_generators_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"guild_id" text NOT NULL,
	"hub_channel_id" text NOT NULL,
	"category_id" text,
	"name_template" text DEFAULT '{user}''s room' NOT NULL,
	"default_user_limit" integer DEFAULT 0 NOT NULL,
	"default_bitrate" integer DEFAULT 0 NOT NULL,
	"auto_text" boolean DEFAULT false NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	"allowed_actions" text DEFAULT '{}' NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
ALTER TABLE "voice_room_generators" ADD CONSTRAINT "voice_room_generators_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
CREATE UNIQUE INDEX "voice_room_generators_guild_hub" ON "voice_room_generators" USING btree ("guild_id","hub_channel_id");
--> statement-breakpoint
CREATE TABLE "voice_rooms" (
	"channel_id" text PRIMARY KEY NOT NULL,
	"guild_id" text NOT NULL,
	"generator_id" integer NOT NULL,
	"owner_id" text NOT NULL,
	"text_channel_id" text,
	"locked" boolean DEFAULT false NOT NULL,
	"ghosted" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
ALTER TABLE "voice_rooms" ADD CONSTRAINT "voice_rooms_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "voice_rooms" ADD CONSTRAINT "voice_rooms_generator_id_voice_room_generators_id_fk" FOREIGN KEY ("generator_id") REFERENCES "public"."voice_room_generators"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
CREATE UNIQUE INDEX "voice_rooms_guild_owner" ON "voice_rooms" USING btree ("guild_id","owner_id");
--> statement-breakpoint
CREATE INDEX "idx_voice_rooms_guild" ON "voice_rooms" USING btree ("guild_id");
