CREATE TABLE "stream_alerts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "stream_alerts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"guild_id" text NOT NULL,
	"platform" text NOT NULL,
	"handle" text NOT NULL,
	"display_name" text NOT NULL,
	"discord_channel_id" text NOT NULL,
	"mention_role_id" text,
	"template" text DEFAULT E'{name} está en directo: {title}\n{url}' NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	"is_live" boolean DEFAULT false NOT NULL,
	"live_id" text,
	"last_title" text,
	"last_checked_at" timestamp with time zone,
	"last_live_at" timestamp with time zone,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
ALTER TABLE "stream_alerts" ADD CONSTRAINT "stream_alerts_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
CREATE UNIQUE INDEX "stream_alerts_guild_platform_handle" ON "stream_alerts" USING btree ("guild_id","platform","handle");
--> statement-breakpoint
CREATE INDEX "idx_stream_alerts_guild" ON "stream_alerts" USING btree ("guild_id");
--> statement-breakpoint
CREATE INDEX "idx_stream_alerts_enabled" ON "stream_alerts" USING btree ("enabled");
