CREATE TABLE "auto_replies" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "auto_replies_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"guild_id" text NOT NULL,
	"trigger" text NOT NULL,
	"match_mode" text DEFAULT 'contains' NOT NULL,
	"response" text NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	"case_sensitive" boolean DEFAULT false NOT NULL,
	"whole_word" boolean DEFAULT false NOT NULL,
	"use_reply" boolean DEFAULT true NOT NULL,
	"cooldown_seconds" integer DEFAULT 0 NOT NULL,
	"allowed_channel_ids" text DEFAULT '[]' NOT NULL,
	"ignored_channel_ids" text DEFAULT '[]' NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
ALTER TABLE "auto_replies" ADD CONSTRAINT "auto_replies_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
CREATE INDEX "idx_auto_replies_guild" ON "auto_replies" USING btree ("guild_id");
