CREATE TABLE "ticket_settings" (
	"guild_id" text PRIMARY KEY NOT NULL,
	"category_id" text,
	"staff_role_ids" text DEFAULT '[]' NOT NULL,
	"name_template" text DEFAULT 'ticket-{n}-{user}' NOT NULL,
	"max_open_per_user" integer DEFAULT 1 NOT NULL,
	"log_channel_id" text,
	"next_number" integer DEFAULT 1 NOT NULL,
	"opener_can_close" boolean DEFAULT true NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ticket_panels" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ticket_panels_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"guild_id" text NOT NULL,
	"channel_id" text,
	"message_id" text,
	"embed_title" text DEFAULT 'Tickets' NOT NULL,
	"embed_description" text DEFAULT 'Pulsa un botón para abrir un ticket.' NOT NULL,
	"embed_color" text DEFAULT '#5865F2' NOT NULL,
	"buttons" text DEFAULT '[]' NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "tickets" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tickets_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"guild_id" text NOT NULL,
	"number" integer NOT NULL,
	"opener_id" text NOT NULL,
	"channel_id" text,
	"type_key" text NOT NULL,
	"status" text DEFAULT 'open' NOT NULL,
	"claimed_by" text,
	"reason" text,
	"close_reason" text,
	"transcript_text" text,
	"opened_at" timestamp with time zone NOT NULL,
	"closed_at" timestamp with time zone,
	"claimed_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "ticket_events" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ticket_events_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"ticket_id" integer NOT NULL,
	"guild_id" text NOT NULL,
	"type" text NOT NULL,
	"actor_id" text,
	"payload" text DEFAULT '{}' NOT NULL,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ticket_participants" (
	"ticket_id" integer NOT NULL,
	"user_id" text NOT NULL,
	"kind" text DEFAULT 'added' NOT NULL,
	CONSTRAINT "ticket_participants_ticket_id_user_id_pk" PRIMARY KEY("ticket_id","user_id")
);
--> statement-breakpoint
ALTER TABLE "ticket_settings" ADD CONSTRAINT "ticket_settings_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "ticket_panels" ADD CONSTRAINT "ticket_panels_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "tickets" ADD CONSTRAINT "tickets_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "ticket_events" ADD CONSTRAINT "ticket_events_ticket_id_tickets_id_fk" FOREIGN KEY ("ticket_id") REFERENCES "public"."tickets"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "ticket_events" ADD CONSTRAINT "ticket_events_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "ticket_participants" ADD CONSTRAINT "ticket_participants_ticket_id_tickets_id_fk" FOREIGN KEY ("ticket_id") REFERENCES "public"."tickets"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
CREATE INDEX "idx_ticket_panels_guild" ON "ticket_panels" USING btree ("guild_id");
--> statement-breakpoint
CREATE UNIQUE INDEX "tickets_guild_number" ON "tickets" USING btree ("guild_id","number");
--> statement-breakpoint
CREATE UNIQUE INDEX "tickets_channel_id_unique" ON "tickets" USING btree ("channel_id");
--> statement-breakpoint
CREATE INDEX "idx_tickets_guild_status" ON "tickets" USING btree ("guild_id","status");
--> statement-breakpoint
CREATE INDEX "idx_tickets_guild_opener" ON "tickets" USING btree ("guild_id","opener_id");
--> statement-breakpoint
CREATE INDEX "idx_ticket_events_ticket" ON "ticket_events" USING btree ("ticket_id");
--> statement-breakpoint
CREATE INDEX "idx_ticket_events_guild_created" ON "ticket_events" USING btree ("guild_id","created_at");
--> statement-breakpoint
CREATE INDEX "idx_ticket_participants_ticket" ON "ticket_participants" USING btree ("ticket_id");
