CREATE TABLE "giveaway_settings" (
	"guild_id" text PRIMARY KEY NOT NULL,
	"manager_role_ids" text DEFAULT '[]' NOT NULL,
	"dm_winners" boolean DEFAULT true NOT NULL,
	"ping_role_id" text,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "giveaways" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "giveaways_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"guild_id" text NOT NULL,
	"channel_id" text NOT NULL,
	"message_id" text,
	"prize" text NOT NULL,
	"description" text DEFAULT '' NOT NULL,
	"winner_count" integer DEFAULT 1 NOT NULL,
	"status" text DEFAULT 'scheduled' NOT NULL,
	"starts_at" timestamp with time zone NOT NULL,
	"ends_at" timestamp with time zone NOT NULL,
	"ended_at" timestamp with time zone,
	"created_by" text NOT NULL,
	"required_role_ids" text DEFAULT '[]' NOT NULL,
	"blocked_role_ids" text DEFAULT '[]' NOT NULL,
	"min_guild_age_days" integer DEFAULT 0 NOT NULL,
	"min_account_age_days" integer DEFAULT 0 NOT NULL,
	"winner_ids" text DEFAULT '[]' NOT NULL,
	"past_winner_ids" text DEFAULT '[]' NOT NULL,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "giveaway_entries" (
	"giveaway_id" integer NOT NULL,
	"user_id" text NOT NULL,
	"entered_at" timestamp with time zone NOT NULL,
	CONSTRAINT "giveaway_entries_giveaway_id_user_id_pk" PRIMARY KEY("giveaway_id","user_id")
);
--> statement-breakpoint
ALTER TABLE "giveaway_settings" ADD CONSTRAINT "giveaway_settings_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "giveaways" ADD CONSTRAINT "giveaways_guild_id_guild_settings_guild_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guild_settings"("guild_id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "giveaway_entries" ADD CONSTRAINT "giveaway_entries_giveaway_id_giveaways_id_fk" FOREIGN KEY ("giveaway_id") REFERENCES "public"."giveaways"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
CREATE INDEX "idx_giveaways_guild_status" ON "giveaways" USING btree ("guild_id","status");
--> statement-breakpoint
CREATE INDEX "idx_giveaways_ends_at" ON "giveaways" USING btree ("ends_at");
--> statement-breakpoint
CREATE INDEX "idx_giveaways_starts_at" ON "giveaways" USING btree ("starts_at");
--> statement-breakpoint
CREATE INDEX "idx_giveaway_entries_giveaway" ON "giveaway_entries" USING btree ("giveaway_id");
