[package]
name = "tobot-delivery"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
tokio.workspace = true
time.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tobot-bus = { path = "../../crates/tobot-bus" }
tobot-outbox = { path = "../../crates/tobot-outbox" }
tobot-persistence = { path = "../../crates/tobot-persistence" }

[lints]
workspace = true
