[package]
name = "tobot-outbox"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
sqlx.workspace = true
thiserror.workspace = true
time.workspace = true
tobot-bus = { path = "../tobot-bus" }
tobot-envelope = { path = "../tobot-envelope" }
tobot-persistence = { path = "../tobot-persistence" }
uuid.workspace = true

[lints]
workspace = true
